### ISSUE TITLE
Cannot run after new update !! Emergency issue 

### ISSUE THREAD

**Issue by TandelK** [splewis/get5-web#38] opened 2017-02-14 16:52 UTC
ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  import flask.ext.cache
/var/www/clanpanel.itgc.ga/get5/__init__.py:33: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  import flask.ext.sqlalchemy
/var/www/clanpanel.itgc.ga/get5/__init__.py:34: ExtDeprecationWarning: Importing flask.ext.openid is deprecated, use flask_openid instead.
  import flask.ext.openid
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/clanpanel.itgc.ga/get5/__init__.py", line 35, in <module>
    import flask_limiter
  File "/usr/local/lib/python2.7/dist-packages/flask_limiter/__init__.py", line 8, in <module>
    from .errors import RateLimitExceeded
  File "/usr/local/lib/python2.7/dist-packages/flask_limiter/errors.py", line 6, in <module>
    from pkg_resources import get_distribution
ImportError: No module named pkg_resources

**Comment by splewis** [comment] 2017-02-15 02:55
It looks like you have an issue with the installation of your packages. (specifically flask_limiter). I'd make sure you actually have all the packages in requirements.txt installed: ``pip install -r requirements.txt``

**Comment by TandelK** [comment] 2017-02-15 08:52
pip install Flask-Limiter==0.9.3
Requirement already satisfied: Flask-Limiter==0.9.3 in ./venv/lib/python2.7/site-packages
Requirement already satisfied: Flask>=0.8 in ./venv/lib/python2.7/site-packages (from Flask-Limiter==0.9.3)
Requirement already satisfied: limits in ./venv/lib/python2.7/site-packages (from Flask-Limiter==0.9.3)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python2.7/site-packages (from Flask-Limiter==0.9.3)
Requirement already satisfied: itsdangerous>=0.21 in ./venv/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.9.3)
Requirement already satisfied: Werkzeug>=0.7 in ./venv/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.9.3)
Requirement already satisfied: Jinja2>=2.4 in ./venv/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.9.3)
Requirement already satisfied: MarkupSafe in ./venv/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.8->Flask-Limiter==0.9.3)
 

I tried to run manually run pip install Flask-Limiter==0.9.3

**Comment by splewis** [comment] 2017-02-16 05:23
Can you open a python shell (maybe inside a virtualenv if you're using one for the webpanel like the README suggests) and import the module, e.g.: 

```
/var/www/get5$ . ./venv/bin/activate
(venv)/var/www/get5$ python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> import flask_limiter
>>> 
```

**Comment by TandelK** [comment] 2017-02-16 06:59
Sean i think issue is with Python and current Ubuntu 16.04 LTS version. I think Python 2.7 is no longer supported in new version of Ubuntu servers, because when i tried to run Virtualenv venv it shows that Virtualenv command not found , after i installed Python 3.5 . virtualenv got installed and is working. If you use new version of Python 3.5 it does not seems to work with Flask even. Some of the Flask module does not seems to be responding properly with Python 3.5 version. If you requrie any type of logs do let me know. Or best open up a gitter chat so all can discuss

**Comment by splewis** [comment] 2017-02-16 07:47
You don't have to use virtualenv, it's just suggested in the readme: https://virtualenv.pypa.io/en/stable/installation/

There's reproducible commands used by the travis testing environment that still succeed (https://github.com/splewis/get5-web/blob/master/.travis.yml), so I think your issue is still an installation problem. 

I don't really care if you have a virtualenv or not. I care if whatever python installation your web panel uses can import flask and flask_limiter. If not, I'd try running ``pip install flask_limiter``.

**Comment by splewis** [comment] 2017-03-12 01:12
Closing since there's no followup.

**Closed by splewis** 2017-03-12 01:12 UTC

**Comment by TandelK** [comment] 2017-03-12 22:55
Yes Sorry for not following up . I reinstalled Ubuntu 14.04 on it and got it working Thanks
